version: "3"

# 声明一个名为network的networks,subnet为network的子网地址,默认网关是177.7.0.1
networks:
  traefik-net:
    external: true
        
# 设置mysql，redis持久化保存
volumes:
  mysql:
  
services:
  web:
    image: registry.cn-zhangjiakou.aliyuncs.com/developer_jk/stdy-hub:1.0
    container_name: stdy-hub-web
    restart: always
    depends_on:
      - server
    command: [ 'nginx-debug', '-g', 'daemon off;' ]
    networks:
       - traefik-net
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.http.routers.stdy-hub-web.entrypoints=websecure"
        - "traefik.http.routers.stdy-hub-web.rule=Host(`study-hub-web.yangzimo.site`)"
        - "traefik.http.services.stdy-hub-web-service.loadbalancer.server.port=8080"

  server:
    image: registry.cn-zhangjiakou.aliyuncs.com/developer_jk/stdy-hub-server:1.0
    container_name: stdy-hub-server
    restart: always
    depends_on:
      - mysql
      - redis
    links:
      - mysql
    networks:
       - traefik-net
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.http.routers.stdy-hub-server.entrypoints=websecure"
        - "traefik.http.routers.stdy-hub-server.rule=Host(`study-hub-api.yangzimo.site`)"
        - "traefik.http.services.stdy-hub-server-service.loadbalancer.server.port=8888"